markdown: kramdown
title: "CoilSnake"
latest_version: "3.33"
windows_download_url: "http://bit.ly/2EWTtmq"
social_media_links:
  twitter: https://twitter.com/_mrtenda
  github: https://github.com/mrtenda/CoilSnake
