markdown: kramdown
title: "CoilSnake"
latest_version: "3.0"
windows_download_url: "http://bit.ly/2sB7IXC"
social_media_links:
  twitter: https://twitter.com/realmrtenda
  github: https://github.com/mrtenda/CoilSnake
